# -*- coding: utf-8 -*-
"""Exercício_Python_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hoOXBnM-el6VE84UJzjfLTBaqNGGnjQI

**Exercício 1 - Aquecimento de Python para Ciência de Dados**

1. Imprima "Hello, World!" no console.
"""

print('hello, world!!!')

"""2. Crie uma variável x com valor 10 e imprima seu valor."""

x = 10
print(x)

"""3. Some dois números e exiba o resultado."""

y = x
print(f'a soma é {y+x}')

"""4. Verifique se um número é par ou ímpar.

"""

if y % 2 == 0:
    print('par')
else:
    print('impar')

"""5. Crie uma função que receba dois números e retorne a soma deles."""

def soma(a, b)->int:
  return a+b
soma(100,-99)

"""6. Crie uma lista com os números de 1 a 5 e imprima-a.

"""

num = [1, 2, 3, 4, 5]
print (num)

"""7. Adicione o número 6 à lista criada na questão anterior.

"""

num.append(6)
print(num)

"""8. Remova o número 3 da lista."""

num.remove(3)
print(num)

"""9. Acesse o terceiro elemento da lista."""

print(num[2])

"""10. Imprima o tamanho da lista."""

print(len(num))

"""11. Crie um dicionário com informações de um carro (marca, modelo, ano)."""

carro = {
    'marca': 'chevrolet',
    'modelo': 'chevete',
    'ano': '2077'
}
print(carro)

"""12. Acesse o valor associado à chave "marca" no dicionário."""

print(carro['marca'])

"""13. Adicione uma nova chave "cor" com valor "preto" ao dicionário."""

carro['pintura'] = "preto"

"""14. Verifique se a chave "modelo" existe no dicionário.

"""

carro.keys()

"""15. Itere sobre as chaves do dicionário e imprima cada uma delas."""

for x in carro.keys():
  print(x)

"""15. Itere sobre as chaves do dicionário e imprima cada uma delas."""

for x in carro.keys():
  print(x)

"""17. Crie uma função que receba uma lista e retorne a soma dos elementos."""

def soma_de_lista(lista):
    soma = sum(lista)
    return soma
print (soma_de_lista(num))

"""18. Crie uma função que receba um dicionário e retorne todas as suas chaves.

"""

def dic_list(dic):
  return dic.keys()
dic_list(carro)

"""
19. Crie uma função que receba um dicionário e imprima chave e valor em linhas separadas."""

def split_dic(dic):
  for i in dic.keys():
    print(i)
  for i in dic.values():
    print(i)
split_dic(carro)

"""20. Crie uma classe chamada Pessoa com atributos nome e idade, e um método que imprima esses dados."""

class Pessoa:
  def __init__(self, nome, idade):
      self.nome = nome
      self.idade = idade

joao = Pessoa('joao', 20)
print(joao.nome)
print(joao.idade)

